### PR TITLE
Replace macros.rs with delegate crate

### PR DESCRIPTION
**Pull request by matthias-t**
It's only necessary for libraries, and the `macros` module is private anyway.
By the way, what does this macro do?

### CODE REVIEW

**Comment by IGI-111** [comment]
This is fine as is, but if you want to you can broaden the scope of this PR to deleting the macro altogether.

The macro itself is a bit of a hack to implement a delegation pattern without a lot of boilerplate but there are now crates to do this like [rust-delegate](https://github.com/chancancode/rust-delegate) so it might be a good thing to just port usages to that.

**Comment by matthias-t** [comment]
I'm on it

**Comment by matthias-t** [comment]
Done!

**Comment by IGI-111** [comment]
Very nice.

**Pull request merged**
